spring:
  application:
    name: agente-rag
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: PROVAS_OAB
    password: Senha123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: 8080
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

# Configuração global do LangChain4j na raiz do YAML
langchain4j:
  google-ai-gemini:
    api-key: AQ.Ab8RN6Ln-sxUHdLdWnj9Dy0ZVyUEyxts690Hukxmf0ugbj4qMA
    chat-model: gemini-3.6-flash
    embedding-model:  gemini-embedding-001

# Configurações específicas da sua aplicação
agente-rag:
  ingestao:
    diretorio-documentos: classpath:documentos/
  rag:
    max-resultados: 5
    limiar-similaridade: 0.7
  tesseract:
    datapath: D:/TESSERACT/tessdata